### ISSUE TITLE
conn.getObservedAddrs is not a function :(

### ISSUE THREAD

**Issue by nicola** [diasdavid/js-libp2p-swarm#57]
Every now and then, when I run the simulation with +10 nodes, it crashes with the following error:

```js
/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/libp2p-swarm/lib/identify.js:88
      var obsMultiaddr = conn.getObservedAddrs()[0];
                              ^

TypeError: conn.getObservedAddrs is not a function
    at .<anonymous> (/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/libp2p-swarm/lib/identify.js:88:31)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Messages._emit (/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/protocol-buffers-stream/index.js:121:40)
    at Messages._onmessage (/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/protocol-buffers-stream/index.js:141:14)
    at Messages._write (/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/protocol-buffers-stream/index.js:94:38)
    at doWrite (/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/mozilla/Proj/cyclon/js-gossip-cyclon/node_modules/readable-stream/lib/_stream_writable.js:3
```

it happens really rarely, and I haven't written a test for this. Is this a known issue or you have an idea of what this could be caused by?

**Comment by diasdavid** [comment]
@nicola which transports are you using? I haven't seen this error, if you can create a test to reproduce it would be awesome!

**Comment by dignifiedquire** [comment]
It would also be good if you can try `console.log`ing what `conn` is that moment

**Comment by nicola** [comment]
@diasdavid I am using TCP only, on the local network.

1. Will write a test or at least find a way to replicate it (it is a nasty one)
2. Will add a console log

**Comment by diasdavid** [comment]
@nicola this should now be fixed :)
